---
# install custom config files
- name: configs
  template:
    dest: "{{item.dest}}"
    src: "{{item.src|default('../templates{0}'.format(item.dest))}}"
    force: "{{item.force|default(True)}}"
    mode: "{{item.mode|default(omit)}}"
    owner: "{{item.owner|default(omit)}}"
    group: "{{item.group|default(omit)}}"
    trim_blocks: "{{item.trim_blocks|default(False)}}"
  with_list: "{{cops_dbsmartbackup_vars.configs}}"
  tags: [dbsmartbackup, configs, dbsmartbackup_configs]
  notify: "{{cops_dbsmartbackup_vars.rhandlers}}"
