---
- tags: [cops_dbsmartbackup, dbsmartbackup]
  block:
  - include_tasks: P1000_users.yml
    tags: [cops_dbsmartbackup_s_users]
    when: [cops_dbsmartbackup_s_users]
  - include_tasks: P2000_layout.yml
    tags: [cops_dbsmartbackup_s_layout]
    when: [cops_dbsmartbackup_s_layout]
  - include_tasks: G9000_fixperms.yml
    tags: [cops_dbsmartbackup_s_first_fixperms]
    when: [cops_dbsmartbackup_s_first_fixperms]
  - include_tasks: P4000_prerequisites.yml
    tags: [cops_dbsmartbackup_s_prerequisites]
    when: [cops_dbsmartbackup_s_prerequisites]
  - include_tasks: P4500_setup.yml
    tags: [cops_dbsmartbackup_s_setup]
    when: [cops_dbsmartbackup_s_setup]
  - include_tasks: P8000_entry_point.yml
    tags: [cops_dbsmartbackup_s_entry_point]
    when: [cops_dbsmartbackup_s_entry_point]
  - include_tasks: P8200_workers.yml
    tags: [cops_dbsmartbackup_s_workers]
    when: [cops_dbsmartbackup_s_workers]
  - include_tasks: P8500_manage_content.yml
    tags: [cops_dbsmartbackup_s_managecontent]
    when: [cops_dbsmartbackup_s_managecontent]
  - include_tasks: G9000_fixperms.yml
    tags: [cops_dbsmartbackup_s_end_fixperms]
    when: [cops_dbsmartbackup_s_end_fixperms]
