---
- when: [cops_dbsmartbackup_s_prerequisites_pkgs]
  tags: [cops_dbsmartbackup_s_prerequisites_pkgs]
  block:
  - name: update & install prerequisites
    package:
      cache_valid_time: '{{60*60}}'
      update_cache: yes
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['debian'] and
            cops_dbsmartbackup_vars.deb_packages is not none and
            cops_dbsmartbackup_vars.deb_packages|length > 0)"
    with_items: "{{cops_dbsmartbackup_vars.deb_packages}}"
  - name: update & install prerequisites
    package:
      update_cache: yes
      enablerepo: epel,epel-testing
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['redhat'] and
            cops_dbsmartbackup_vars.rh_packages is not none and
            cops_dbsmartbackup_vars.rh_packages|length > 0)"
    with_items: "{{cops_dbsmartbackup_vars.rh_packages}}"
- include_role: {name: corpusops.roles/services_db_postgresql_client}
  tags: [cops_dbsmartbackup_s_prerequisites_client_postgresql]
  when: [cops_dbsmartbackup_s_prerequisites_client_postgresql]
- include_role: {name: corpusops.roles/services_backup_dbsmartbackup}
  tags: [cops_dbsmartbackup_s_prerequisites_dbsmartbackup]
  when: [cops_dbsmartbackup_s_prerequisites_dbsmartbackup]
