---
- name: configs
  template:
    dest: "{{item.dest}}"
    src: "{{item.src|default('../templates{0}'.format(item.dest))}}"
    mode: "{{item.mode|default(omit)}}"
    force: "{{item.force|default(True)}}"
    owner: "{{item.owner|default(omit)}}"
    group: "{{item.group|default(omit)}}"
    trim_blocks: "{{item.trim_blocks|default(False)}}"
  with_list: "{{cops_dbsmartbackup_ep_configs}}"
  tags: [cops_dbsmartbackup_s_entry_point]
  when: "cops_dbsmartbackup_s_entry_point"
# this will fail on non systemd hosts on purpose !
# if we have activated the reconfigure units (docker mode essentially)
- cops_service:
    enabled: "{{cops_dbsmartbackup_vars.activated | ternary(True, False)}}"
    daemon_reload: yes
    name: "{{item}}"
  loop: "{{cops_dbsmartbackup_vars.reconfigure_services}}"
