---
version: '3.5'
networks: {dbsmartbackup_net: {ipam: {config: [{subnet: "172.19.115.0/24"}], driver: default}, driver: bridge}}
# Build with:
#  docker build --squash -t corpusops/dbsmartbackup -f Dockerfile [--build-arg=SKIP_COPS_UPDATE=y]
# Start with:
#  docker-compose -f d*-compose.yml up -t 0 -d --force-recreate dbsmartbackup
x-image: &image_template
  image: "corpusops/dbsmartbackup"
  environment:
  - "DOCKER_SKIP_START=${DOCKER_SKIP_START-}"
  - |
    A_RECONFIGURE=---
    ---
    only_steps: true
    cops_dbsmartbackup_lifecycle_app_push_code: false
    cops_dbsmartbackup_s_docker_reconfigure: true
    cops_dbsmartbackup_s_first_fixperms: true
    cops_dbsmartbackup_s_setup: true
    cops_dbsmartbackup_s_manage_content: false
  - |
    A_POSTCONFIGURE=---
    ---
    only_steps: true
    cops_dbsmartbackup_lifecycle_app_push_code: false
    cops_dbsmartbackup_s_manage_content: true
  command: >
    sh -c 'if [ "x$DOCKER_SKIP_START" != x ];
    then while true;do echo sleeping;sleep 65535;done
    else exec /app_entry_point;
    fi'
  # for now this is a bloat image-as-a-vm to make a dev env ligther than a vagrant VM
  tmpfs: [/run, /run/lock]
  volumes: &image_volumes
  # systemd
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  # data
  - "./local/setup:/setup"
  - "./local/data/backups:/srv/backups"
  # Remember: /setup/rootfs/ is synced inside the container /
    networks: {dbsmartbackup_net: {ipv4_address: "172.19.115.3"}}
services:
  dbsmartbackup:
    <<:  [ *image_template ]
