---
# generate password on remote box if not found
- name: "dbsmartbackup secret generation: {{dbsmartbackupsecret}}"
  include_role:
    name: corpusops.roles/get_secret_variable
  vars:
    _cops_get_secret_variable:
      name: "cops_dbsmartbackup_{{dbsmartbackupsecret}}"
      path: "/etc/dbsmartbackup-{{cops_dbsmartbackup_vars.name}}-secrets"
  when: not vars.get('cops_dbsmartbackup_{0}'.format(dbsmartbackupsecret), None)
  no_log: "{{not (cops_vars_debug|default(false))}}"
- debug:
    var: "{{'cops_dbsmartbackup_{0}'.format(dbsmartbackupsecret)}}"
  register: cops_secret_value
  no_log: "{{not (cops_vars_debug|default(false))}}"
- name: "Update registry with {{dbsmartbackupsecret}}"
  include_jinja_vars:
    content: |
      ---
      {% set d = dbsmartbackupsecret %}
      {% set p = 'cops_dbsmartbackup_' %}
      {% set v = p+d %}
      {% set n = p+'vars' %}
      {% set _vars = {} %}
      {% set _ = _vars.update(cops_secret_value) %}
      {{(_vars | copsf_registry(p, namespaced=vars[n]))[0]| to_json }}
  no_log: "{{not (cops_vars_debug|default(false))}}"
