---
- listen: restart_cops_drupal_systemd
  become: true
  shell: systemctl daemon-reload
  when: "(cops_drupal_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr == 'systemd'))"

- listen: restart_cops_dbsmartbackup
  become: true
  systemd:
    daemon_reload: yes
    state: restarted
    name: "{{item}}"
  with_items: "{{cops_dbsmartbackup_vars.services}}"
  when: "(cops_dbsmartbackup_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr == 'systemd'))"
- listen: restart_cops_dbsmartbackup
  become: true
  cops_service:
    state: restarted
    name: "{{item}}"
  with_items: "{{cops_dbsmartbackup_vars.services}}"
  when: "(cops_dbsmartbackup_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr != 'systemd'))"
- listen: reload_cops_dbsmartbackup
  become: true
  systemd:
    daemon_reload: yes
    state: reloaded
    name: "{{item}}"
  with_items: "{{cops_dbsmartbackup_vars.services}}"
  when: "(cops_dbsmartbackup_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr == 'systemd'))"
- listen: reload_cops_dbsmartbackup
  become: true
  cops_service:
    state: reloaded
    name: "{{item}}"
  with_items: "{{cops_dbsmartbackup_vars.services}}"
  when: "(cops_dbsmartbackup_vars.activated and
          corpusops_vars.has_services_manager and
          (ansible_service_mgr != 'systemd'))"
